
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2022 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgroup3.h"

/*
* The configuration table for devices
*/

XGroup3_Config XGroup3_ConfigTable[XPAR_XGROUP3_NUM_INSTANCES] =
{
	{
		XPAR_GROUP3_0_DEVICE_ID,
		XPAR_GROUP3_0_S_AXI_CONTROL_BASEADDR
	}
};


